# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory\
$fill\
$cmd_duration\
$git_branch\
$line_break\
$character
"""

[fill]
symbol = " "